
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/layouts/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Provider } from "react-redux";
import { store } from "@/redux/store/store";
import Providers from "@/components/provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "boAt Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers >
        <Navbar/>
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  );
}
